export function exportAsText(contract: string, partyA: string, partyB: string) {
  const content = `CONFIDENTIALITY AND NON-DISCLOSURE AGREEMENT

Generated by ContractDraft
Date: ${new Date().toLocaleDateString()}

Between: ${partyA}
And: ${partyB}

---

${contract}

---
End of Agreement
`

  const blob = new Blob([content], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = `NDA-${partyA.replace(/\s+/g, "-")}-${Date.now()}.txt`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export async function exportAsPDF(contract: string, partyA: string, partyB: string) {
  const html2pdf = (await import("html2pdf.js")).default

  const element = document.createElement("div")
  element.innerHTML = `
    <div style="font-family: 'Times New Roman', serif; padding: 40px; line-height: 1.6; color: #000; background: #fff;">
      <h1 style="text-align: center; margin-bottom: 30px;">NON-DISCLOSURE AGREEMENT</h1>
      <p style="text-align: center; margin-bottom: 20px; font-size: 12px;">
        Between: <strong>${partyA}</strong><br/>
        And: <strong>${partyB}</strong><br/>
        Date: ${new Date().toLocaleDateString()}
      </p>
      <hr style="margin: 30px 0;">
      <div style="white-space: pre-wrap; font-size: 11px;">
        ${contract.replace(/</g, "&lt;").replace(/>/g, "&gt;")}
      </div>
    </div>
  `

  const options = {
    margin: 10,
    filename: `NDA-${partyA.replace(/\s+/g, "-")}-${Date.now()}.pdf`,
    image: { type: "jpeg" as const, quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { orientation: "portrait" as const, unit: "mm" as const, format: "a4" as const },
  }

  html2pdf().set(options).from(element).save()
}

export function printContract(contract: string) {
  const printWindow = window.open("", "", "width=800,height=600")
  if (!printWindow) return

  const content = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>NDA - Print Preview</title>
        <style>
          body {
            font-family: 'Times New Roman', serif;
            padding: 40px;
            line-height: 1.6;
            color: #000;
          }
          h1 {
            text-align: center;
            margin-bottom: 30px;
          }
          @media print {
            body { margin: 0; padding: 20px; }
          }
        </style>
      </head>
      <body>
        <h1>NON-DISCLOSURE AGREEMENT</h1>
        <pre style="white-space: pre-wrap; font-family: 'Times New Roman', serif;">${contract}</pre>
        <script>
          window.print();
          window.onafterprint = function() { window.close(); }
        </script>
      </body>
    </html>
  `

  printWindow.document.write(content)
  printWindow.document.close()
}
